DOMAIN = "hsem"
NAME = "Huawei Solar Energy Management"
ICON = "mdi:power"

DEFAULT_HSEM_ENERGI_DATA_SERVICE_IMPORT = "sensor.energi_data_service"
DEFAULT_HSEM_ENERGI_DATA_SERVICE_EXPORT = "sensor.energi_data_service_produktion"
DEFAULT_HSEM_HUAWEI_SOLAR_BATTERIES_WORKING_MODE = "select.battery_working_mode"
DEFAULT_HSEM_HUAWEI_SOLAR_BATTERIES_STATE_OF_CAPACITY = "sensor.battery_state_of_capacity"
DEFAULT_HSEM_HUAWEI_SOLAR_INVERTER_ACTIVE_POWER_CONTROL = "sensor.inverter_active_power_control"
DEFAULT_HSEM_HOUSE_CONSUMPTION_POWER = "sensor.power_house_load"
DEFAULT_HSEM_SOLAR_PRODUCTION_POWER = "sensor.power_inverter_input_total"
DEFAULT_HSEM_SOLCAST_PV_FORECAST_FORECAST_TODAY = "sensor.solcast_pv_forecast_forecast_today"
DEFAULT_HSEM_SOLCAST_PV_FORECAST_FORECAST_TOMORROW = "sensor.solcast_pv_forecast_forecast_tomorrow"
