"""Pure data-mapping functions extracted from :mod:`coordinator`.

Responsibility
--------------
Build typed dataclass instances (``PlannerInput``, ``HourlyRecommendation``, …)
from raw coordinator state.  **No HA runtime dependencies** — all functions
here accept plain Python values and return plain dataclasses, making them
independently unit-testable.

Usage
-----
These functions are called by :class:`HSEMDataUpdateCoordinator` during the
update cycle.  External code should never need to import from this module
directly.
"""

from __future__ import annotations

from datetime import timedelta

from custom_components.hsem.models.battery_schedule_input import BatteryScheduleInput
from custom_components.hsem.models.hourly_consumption_average import (
    HourlyConsumptionAverage,
)
from custom_components.hsem.models.hourly_recommendation import HourlyRecommendation
from custom_components.hsem.models.live_state import LiveState
from custom_components.hsem.models.planner_input import PlannerInput
from custom_components.hsem.models.price_point import PricePoint
from custom_components.hsem.models.sensor_config import SensorConfig
from custom_components.hsem.models.solcast_slot import SolcastSlot
from custom_components.hsem.utils.capacity_learner import CapacityLearner
from custom_components.hsem.utils.conversion import convert_to_float, convert_to_int
from custom_components.hsem.utils.datetime_utils import now as hsem_now
from custom_components.hsem.utils.misc import (
    calculate_recommended_threshold,
    get_max_discharge_power,
)


def _resolve_max_discharge_power_w(live: LiveState) -> float | None:
    """Return the battery's physical max discharge power for the planner.

    The planner input must reflect the battery's *capability*, not the
    currently commanded value of the ``maximum_discharging_power`` number
    entity.  The applier writes that entity in two situations:

    - the rated-capacity maximum (normal operation), and
    - the EV discharge cap (issue #592) — a much smaller value (e.g. ~321 W)
      that protects the battery from feeding an actively charging EV.

    Reading the entity back while the EV cap is active feeds the capped
    value into the planner as the horizon-wide discharge limit — the
    classic feedback loop observed in the beta7 logs where every slot was
    limited to ``discharge=0.073 kWh`` (321 W × 15 min) and the battery
    could never cover evening house load.  Beta8 narrowed the substitution
    to ``any_ev_charging`` cycles only, but a single EV-status flicker let
    the capped value slip through on an off-schedule run.

    The physical capability is therefore **always** derived from the rated
    capacity (same formula the applier uses for the uncapped write) — never
    from the live entity read-back.  The read-back is a *commanded* value,
    not a capability: besides the EV cap, a brief EV-status flicker (boolean
    sensor bouncing off for one cycle) would otherwise let a still-capped
    entity poison an off-schedule planner run (observed in beta8: one
    irregular cycle planned the whole horizon at ``max_discharge/slot
    =0.010`` after the EV boolean dropped out for a single poll).

    Args:
        live: Live state snapshot.

    Returns:
        Max discharge power in Watts, or ``None`` when the rated capacity
        is unavailable.
    """
    rated_wh = convert_to_int(live.huawei_batteries_rated_capacity_wh)
    if rated_wh is not None and rated_wh > 0:
        return float(get_max_discharge_power(rated_wh))
    # Degraded fallback: no rated capacity known — use the live read-back.
    return convert_to_float(live.huawei_batteries_max_discharge_power_w) or None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_planner_input(
    *,
    cfg: SensorConfig,
    live: LiveState,
    hourly_recommendations: list[HourlyRecommendation],
    batteries_schedules: list,
    previous_winner_name: str | None,
    previous_winner_score: float,
    ev_session_kw: dict[str, float] | None = None,
    capacity_learner: CapacityLearner | None = None,
    dynamic_discharge_floor_pct: float | None = None,
) -> PlannerInput:
    """Assemble a :class:`PlannerInput` from the coordinator's current pipeline state.

    Args:
        cfg: Current sensor configuration.
        live: Live HA entity state snapshot.
        hourly_recommendations: Recommendation slots generated by
            :func:`generate_recommendation_intervals`.
        batteries_schedules: Parsed battery schedule objects.
        previous_winner_name: Winning candidate name from the previous
            planner run, or ``None`` for the first run.
        previous_winner_score: Score of the winning candidate from the
            previous planner run.

    Returns:
        A fully populated :class:`PlannerInput` ready for the planner engine.
    """
    now = hsem_now()

    # Dedup key is (day_offset, hour) so that tomorrow's slots are kept
    # separately from today's even when they share the same wall-clock hour.
    seen_day_hours: set[tuple[int, int]] = set()
    consumption_averages: list[HourlyConsumptionAverage] = []
    price_points: list[PricePoint] = []
    solcast_slots: list[SolcastSlot] = []

    # slots_per_hour is used to up-scale per-slot consumption averages to
    # hourly totals for the planner engine.  Prices and Solcast PV are now
    # stored at face value by the populator (no divide/multiply round-trip),
    # so slots_per_hour is only needed for the consumption averages below.
    slots_per_hour = 60.0 / cfg.recommendation_interval_minutes

    # Midnight of the planning day — used to compute per-slot day_offset.
    planning_midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)

    for rec in hourly_recommendations:
        h = rec.start.hour
        # Compute day_offset: number of whole calendar days between
        # planning midnight and this slot's date.  This preserves the
        # distinction between today's hour-3 and tomorrow's hour-3 for
        # multi-day planning horizons (e.g. 48 h or 72 h).
        day_offset = (rec.start.date() - planning_midnight.date()).days

        # Prices are per-slot: 15-min price data must survive to the planner
        # as distinct quarter-hourly points (issue #720).  Consumption
        # averages and Solcast PV are genuinely hour-granular and stay
        # deduplicated below.
        slot_in_day = (rec.start.hour * 60 + rec.start.minute) // int(
            cfg.recommendation_interval_minutes
        )
        # Prices are stored at face value by the populator (no scaling).
        price_points.append(
            PricePoint(
                hour=h,
                import_price=round(rec.import_price, 5),
                export_price=round(rec.export_price, 5),
                day_offset=day_offset,
                slot_in_day=slot_in_day,
            )
        )

        day_hour_key = (day_offset, h)
        if day_hour_key in seen_day_hours:
            continue
        seen_day_hours.add(day_hour_key)

        consumption_averages.append(
            HourlyConsumptionAverage(
                hour=h,
                avg_1d=round(rec.avg_house_consumption_1d_kwh * slots_per_hour, 3),
                avg_3d=round(rec.avg_house_consumption_3d_kwh * slots_per_hour, 3),
                avg_7d=round(rec.avg_house_consumption_7d_kwh * slots_per_hour, 3),
                avg_14d=round(rec.avg_house_consumption_14d_kwh * slots_per_hour, 3),
                day_offset=day_offset,
            )
        )
        solcast_slots.append(
            SolcastSlot(
                hour=h,
                pv_estimate=round(rec.solcast_pv_estimate_kwh, 3),
                day_offset=day_offset,
            )
        )

    battery_schedules = [
        BatteryScheduleInput(
            enabled=s.enabled,
            start=s.start,
            end=s.end,
        )
        for s in batteries_schedules
    ]

    _cycles = convert_to_int(cfg.batteries_expected_cycles)
    _w1d = convert_to_int(cfg.house_consumption_energy_weight_1d)
    _w3d = convert_to_int(cfg.house_consumption_energy_weight_3d)
    _w7d = convert_to_int(cfg.house_consumption_energy_weight_7d)
    _w14d = convert_to_int(cfg.house_consumption_energy_weight_14d)

    # Prefer the bounded delivered-energy-credited SoC over the raw reported
    # value so a vehicle API that updates SoC far less often than charger
    # power does not stall the planner's view of progress (issue #789).
    ev_soc_pct = convert_to_float(live.ev.effective_soc_pct)
    if ev_soc_pct is None:
        ev_soc_pct = convert_to_float(live.ev_planned_load_current_soc_pct)
    ev_second_soc_pct = convert_to_float(live.ev_second.effective_soc_pct)
    if ev_second_soc_pct is None:
        ev_second_soc_pct = convert_to_float(
            live.ev_second_planned_load_current_soc_pct
        )

    return PlannerInput(
        now_iso=now.isoformat(),
        interval_minutes=cfg.recommendation_interval_minutes,
        interval_length_hours=cfg.recommendation_interval_length,
        battery_soc_pct=convert_to_float(live.huawei_batteries_soc_pct) or 50.0,
        battery_rated_capacity_kwh=(
            convert_to_float(live.huawei_batteries_rated_capacity_wh) or 0.0
        )
        / 1000.0,
        battery_end_of_discharge_soc_pct=convert_to_float(
            live.huawei_batteries_end_of_discharge_soc_pct or 5.0
        )
        or 5.0,
        battery_max_soc_pct=convert_to_float(
            live.huawei_batteries_charging_cutoff_capacity_pct
        )
        or 100.0,
        battery_max_charge_power_w=(
            convert_to_float(live.huawei_batteries_max_charge_power_w) or 5000.0
        ),
        battery_max_discharge_power_w=_resolve_max_discharge_power_w(live),
        battery_charge_efficiency_pct=convert_to_float(cfg.batteries_charge_efficiency)
        or 95.0,
        battery_discharge_efficiency_pct=convert_to_float(
            cfg.batteries_discharge_efficiency
        )
        or 95.0,
        battery_purchase_price=convert_to_float(cfg.batteries_purchase_price) or 0.0,
        battery_expected_cycles=_cycles if _cycles is not None else 6000,
        battery_cycle_cost_per_kwh=convert_to_float(cfg.batteries_cycle_cost) or 0.0,
        battery_capacity_loss_pct=cfg.batteries_capacity_loss_pct,
        weight_1d=_w1d if _w1d is not None else 25,
        weight_3d=_w3d if _w3d is not None else 30,
        weight_7d=_w7d if _w7d is not None else 30,
        weight_14d=_w14d if _w14d is not None else 15,
        consumption_averages=consumption_averages,
        price_points=price_points,
        solcast_slots=solcast_slots,
        battery_schedules=battery_schedules,
        excess_export_enabled=bool(cfg.batteries_enable_excess_export),
        excess_export_discharge_buffer_pct=convert_to_float(
            cfg.batteries_excess_export_discharge_buffer
        )
        or 10.0,
        excess_export_price_threshold=calculate_recommended_threshold(
            purchase_price=convert_to_float(cfg.batteries_purchase_price) or 0.0,
            expected_cycles=_cycles if _cycles is not None else 6000,
            usable_capacity=(
                capacity_learner.learned_capacity_kwh
                if capacity_learner is not None
                and capacity_learner.learned_capacity_kwh is not None
                else live.battery_usable_capacity_kwh
            ),
        ),
        # Per-slot hard floor for intentional battery-to-grid export (issue #752).
        battery_export_min_price=(
            convert_to_float(cfg.batteries_export_min_price) or 0.0
        ),
        export_min_price=convert_to_float(cfg.export_electricity_min_price) or 0.0,
        main_fuse_amps=(float(cfg.main_fuse_amps) if cfg.main_fuse_amps > 0 else None),
        main_fuse_phases=cfg.main_fuse_phases,
        max_grid_export_power_kw=(
            float(cfg.max_grid_export_power_kw)
            if cfg.max_grid_export_power_kw > 0
            else None
        ),
        months_winter=list(cfg.months_winter or []),
        house_power_includes_ev=bool(cfg.house_power_includes_ev_charger_power),
        live_solar_production_w=convert_to_float(live.solar_production_power_w) or 0.0,
        live_house_consumption_w=convert_to_float(live.house_consumption_power_w)
        or 0.0,
        is_read_only=bool(cfg.read_only),
        # EV planned load
        ev_planned_load_enabled=bool(cfg.ev_planned_load_enabled),
        ev_planned_load_connected=bool(live.ev_planned_load_connected),
        ev_planned_load_smart_charging_enabled=bool(
            live.ev_planned_load_smart_charging_enabled
        ),
        ev_planned_load_current_soc_pct=ev_soc_pct or 0.0,
        ev_planned_load_target_soc_pct=convert_to_float(
            live.ev_planned_load_target_soc_pct
        )
        or 80.0,
        ev_planned_load_battery_capacity_kwh=convert_to_float(
            cfg.ev_planned_load_battery_capacity_kwh
        )
        or 0.0,
        ev_planned_load_charger_power_kw=convert_to_float(
            cfg.ev_planned_load_charger_power_kw
        )
        or 0.0,
        ev_planned_load_charger_efficiency_pct=convert_to_float(
            cfg.ev_planned_load_charger_efficiency_pct
        )
        or 100.0,
        ev_planned_load_charger_min_power_w=convert_to_float(
            cfg.ev_planned_load_charger_min_power_w
        )
        or 1380.0,
        ev_planned_load_deadline=live.ev_planned_load_deadline,
        ev_planned_load_base_load_includes_ev=bool(
            cfg.house_power_includes_ev_charger_power
        ),
        ev_planned_load_charger_phase_topology=(
            cfg.ev_planned_load_charger_phase_topology
        ),
        ev_planned_allow_charge_past_target_soc=bool(
            cfg.ev.allow_charge_past_target_soc
        ),
        ev_past_target_confidence_factor=convert_to_float(
            cfg.ev.past_target_confidence_factor
        )
        or 0.9,
        # Second EV planned load
        ev_second_planned_load_enabled=bool(cfg.ev_second_planned_load_enabled),
        ev_second_planned_load_connected=bool(live.ev_second_planned_load_connected),
        ev_second_planned_load_smart_charging_enabled=bool(
            live.ev_second_planned_load_smart_charging_enabled
        ),
        ev_second_planned_load_current_soc_pct=ev_second_soc_pct or 0.0,
        ev_second_planned_load_target_soc_pct=convert_to_float(
            live.ev_second_planned_load_target_soc_pct
        )
        or 80.0,
        ev_second_planned_load_battery_capacity_kwh=convert_to_float(
            cfg.ev_second_planned_load_battery_capacity_kwh
        )
        or 0.0,
        ev_second_planned_load_charger_power_kw=convert_to_float(
            cfg.ev_second_planned_load_charger_power_kw
        )
        or 0.0,
        ev_second_planned_load_charger_efficiency_pct=convert_to_float(
            cfg.ev_second_planned_load_charger_efficiency_pct
        )
        or 100.0,
        ev_second_planned_load_charger_min_power_w=convert_to_float(
            cfg.ev_second_planned_load_charger_min_power_w
        )
        or 1380.0,
        ev_second_planned_load_deadline=live.ev_second_planned_load_deadline,
        ev_second_planned_load_base_load_includes_ev=bool(
            cfg.house_power_includes_ev_charger_power
        ),
        ev_second_planned_load_charger_phase_topology=(
            cfg.ev_second_planned_load_charger_phase_topology
        ),
        ev_second_allow_charge_past_target_soc=bool(
            cfg.ev_second.allow_charge_past_target_soc
        ),
        ev_second_past_target_confidence_factor=convert_to_float(
            cfg.ev_second.past_target_confidence_factor
        )
        or 0.9,
        time_discount_rate=0.995,
        # Planner hysteresis (issue #372)
        planner_hysteresis_enabled=bool(cfg.planner_hysteresis_enabled),
        planner_hysteresis_absolute=(
            convert_to_float(cfg.planner_hysteresis_absolute) or 0.0
        ),
        planner_hysteresis_percentage=(
            convert_to_float(cfg.planner_hysteresis_percentage) or 0.0
        ),
        previous_winner_name=previous_winner_name,
        previous_winner_score=previous_winner_score,
        ev_session_charge_kw=(ev_session_kw.get("ev") if ev_session_kw else None),
        ev_second_session_charge_kw=(
            ev_session_kw.get("ev_second") if ev_session_kw else None
        ),
        dynamic_discharge_floor_pct=dynamic_discharge_floor_pct,
    )


def generate_recommendation_intervals(
    interval_minutes: int, total_hours: int
) -> list[HourlyRecommendation]:
    """Generate empty recommendation slots from midnight for ``total_hours`` hours.

    Args:
        interval_minutes: Width of each slot in minutes.
        total_hours: Planning horizon in hours.

    Returns:
        A list of :class:`HourlyRecommendation` objects with all numeric
        fields initialised to ``0.0``.
    """
    now = hsem_now()
    start_time = now.replace(hour=0, minute=0, second=0, microsecond=0)
    steps = int((total_hours * 60) / interval_minutes)

    intervals = []
    for i in range(steps):
        t_start = start_time + timedelta(minutes=i * interval_minutes)
        t_end = t_start + timedelta(minutes=interval_minutes)
        intervals.append(
            HourlyRecommendation(
                avg_house_consumption_kwh=0.0,
                avg_house_consumption_1d_kwh=0.0,
                avg_house_consumption_3d_kwh=0.0,
                avg_house_consumption_7d_kwh=0.0,
                avg_house_consumption_14d_kwh=0.0,
                batteries_charged_kwh=0.0,
                batteries_discharged_kwh=0.0,
                end=t_end,
                estimated_battery_capacity_kwh=0.0,
                estimated_battery_soc_pct=0,
                estimated_cost_currency=0.0,
                estimated_net_consumption_kwh=0.0,
                ev_planned_load_kwh=0.0,
                export_price=0.0,
                grid_export_kwh=0.0,
                grid_import_kwh=0.0,
                import_price=0.0,
                recommendation=None,
                solcast_pv_estimate_kwh=0.0,
                start=t_start,
            )
        )
    return intervals
