"""Pure data-mapping functions extracted from :mod:`coordinator`.

Responsibility
--------------
Build typed dataclass instances (``PlannerInput``, ``HourlyRecommendation``, …)
from raw coordinator state.  **No HA runtime dependencies** — all functions
here accept plain Python values and return plain dataclasses, making them
independently unit-testable.

Usage
-----
These functions are called by :class:`HSEMDataUpdateCoordinator` during the
update cycle.  External code should never need to import from this module
directly.
"""

from __future__ import annotations

from datetime import timedelta

from custom_components.hsem.models.hourly_recommendation import HourlyRecommendation
from custom_components.hsem.models.live_state import LiveState
from custom_components.hsem.models.planner_inputs import (
    BatteryScheduleInput,
    HourlyConsumptionAverage,
    PlannerInput,
    PricePoint,
    SolcastSlot,
)
from custom_components.hsem.models.sensor_config import SensorConfig
from custom_components.hsem.utils.datetime_utils import now as hsem_now
from custom_components.hsem.utils.misc import (
    calculate_recommended_threshold,
    convert_to_float,
    convert_to_int,
)

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_planner_input(
    *,
    cfg: SensorConfig,
    live: LiveState,
    hourly_recommendations: list[HourlyRecommendation],
    batteries_schedules: list,
    previous_winner_name: str | None,
    previous_winner_score: float,
) -> PlannerInput:
    """Assemble a :class:`PlannerInput` from the coordinator's current pipeline state.

    Args:
        cfg: Current sensor configuration.
        live: Live HA entity state snapshot.
        hourly_recommendations: Recommendation slots generated by
            :func:`generate_recommendation_intervals`.
        batteries_schedules: Parsed battery schedule objects.
        previous_winner_name: Winning candidate name from the previous
            planner run, or ``None`` for the first run.
        previous_winner_score: Score of the winning candidate from the
            previous planner run.

    Returns:
        A fully populated :class:`PlannerInput` ready for the planner engine.
    """
    now = hsem_now()

    # Dedup key is (day_offset, hour) so that tomorrow's slots are kept
    # separately from today's even when they share the same wall-clock hour.
    seen_day_hours: set[tuple[int, int]] = set()
    consumption_averages: list[HourlyConsumptionAverage] = []
    price_points: list[PricePoint] = []
    solcast_slots: list[SolcastSlot] = []

    # Number of recommendation slots that fit inside one wall-clock hour.
    # Used to up-scale per-slot energy values back to hourly totals before
    # passing them to the planner engine (which works in Wh per hour).
    slots_per_hour = 60.0 / cfg.recommendation_interval_minutes

    # ------------------------------------------------------------------
    # Price interval semantics — see also hourly_data_populator.py
    # ------------------------------------------------------------------
    # `price_share` is the ratio of the price update interval to the slot width:
    #
    #   price_share = electricity_price_update_interval / recommendation_interval_minutes
    #
    # In `hourly_data_populator._async_update_hourly_field`, each price was
    # divided by `price_share` before storing into the per-slot recommendation
    # object.  Here we multiply it back to recover the original price rate
    # (currency/kWh) before handing it to the planner.
    #
    # This forward-and-back pair is intentional: the divide converts the price
    # to a per-slot representation suitable for matching slot boundaries, while
    # the multiply here converts it back to the original hourly rate required by
    # the planner's cost function.
    #
    # Common configurations:
    #   Price 60 min / slots 15 min  →  price_share = 4.0
    #   Price 30 min / slots 15 min  →  price_share = 2.0
    #   Price 15 min / slots 15 min  →  price_share = 1.0  (no-op)
    #   Price 60 min / slots 60 min  →  price_share = 1.0  (no-op)
    price_share = (
        cfg.electricity_price_update_interval / cfg.recommendation_interval_minutes
    )

    # Midnight of the planning day — used to compute per-slot day_offset.
    planning_midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)

    for rec in hourly_recommendations:
        h = rec.start.hour
        # Compute day_offset: number of whole calendar days between
        # planning midnight and this slot's date.  This preserves the
        # distinction between today's hour-3 and tomorrow's hour-3 for
        # multi-day planning horizons (e.g. 48 h or 72 h).
        day_offset = (rec.start.date() - planning_midnight.date()).days
        day_hour_key = (day_offset, h)
        if day_hour_key in seen_day_hours:
            continue
        seen_day_hours.add(day_hour_key)

        consumption_averages.append(
            HourlyConsumptionAverage(
                hour=h,
                avg_1d=round(rec.avg_house_consumption_1d_kwh * slots_per_hour, 3),
                avg_3d=round(rec.avg_house_consumption_3d_kwh * slots_per_hour, 3),
                avg_7d=round(rec.avg_house_consumption_7d_kwh * slots_per_hour, 3),
                avg_14d=round(rec.avg_house_consumption_14d_kwh * slots_per_hour, 3),
                day_offset=day_offset,
            )
        )
        # Multiply by price_share to reverse the per-slot divide applied during
        # population; the planner receives the original currency/kWh rate.
        price_points.append(
            PricePoint(
                hour=h,
                import_price=round(rec.import_price * price_share, 5),
                export_price=round(rec.export_price * price_share, 5),
                day_offset=day_offset,
            )
        )
        solcast_slots.append(
            SolcastSlot(
                hour=h,
                pv_estimate=round(rec.solcast_pv_estimate_kwh * slots_per_hour, 3),
                day_offset=day_offset,
            )
        )

    battery_schedules = [
        BatteryScheduleInput(
            enabled=s.enabled,
            start=s.start,
            end=s.end,
        )
        for s in batteries_schedules
    ]

    return PlannerInput(
        now_iso=now.isoformat(),
        interval_minutes=cfg.recommendation_interval_minutes,
        interval_length_hours=cfg.recommendation_interval_length,
        battery_soc_pct=convert_to_float(live.huawei_batteries_soc_pct) or 50.0,
        battery_rated_capacity_kwh=(
            convert_to_float(live.huawei_batteries_rated_capacity_wh) or 0.0
        )
        / 1000.0,
        battery_end_of_discharge_soc_pct=convert_to_float(
            live.huawei_batteries_end_of_discharge_soc_pct or 5.0
        )
        or 5.0,
        battery_max_soc_pct=convert_to_float(
            live.huawei_batteries_charging_cutoff_capacity_pct
        )
        or 100.0,
        battery_max_charge_power_w=convert_to_float(
            live.huawei_batteries_max_charge_power_w
        )
        or 5000.0,
        battery_max_discharge_power_w=convert_to_float(
            live.huawei_batteries_max_discharge_power_w
        )
        or None,
        battery_charge_efficiency_pct=convert_to_float(cfg.batteries_charge_efficiency)
        or 95.0,
        battery_discharge_efficiency_pct=convert_to_float(
            cfg.batteries_discharge_efficiency
        )
        or 95.0,
        battery_purchase_price=convert_to_float(cfg.batteries_purchase_price) or 0.0,
        battery_expected_cycles=(
            v
            if (v := convert_to_int(cfg.batteries_expected_cycles)) is not None
            else 6000
        ),
        battery_cycle_cost_per_kwh=convert_to_float(cfg.batteries_cycle_cost) or 0.0,
        weight_1d=(
            v
            if (v := convert_to_int(cfg.house_consumption_energy_weight_1d)) is not None
            else 25
        ),
        weight_3d=(
            v
            if (v := convert_to_int(cfg.house_consumption_energy_weight_3d)) is not None
            else 30
        ),
        weight_7d=(
            v
            if (v := convert_to_int(cfg.house_consumption_energy_weight_7d)) is not None
            else 30
        ),
        weight_14d=(
            v
            if (v := convert_to_int(cfg.house_consumption_energy_weight_14d))
            is not None
            else 15
        ),
        consumption_averages=consumption_averages,
        price_points=price_points,
        solcast_slots=solcast_slots,
        battery_schedules=battery_schedules,
        excess_export_enabled=bool(cfg.batteries_enable_excess_export),
        excess_export_discharge_buffer_pct=convert_to_float(
            cfg.batteries_excess_export_discharge_buffer
        )
        or 10.0,
        excess_export_price_threshold=calculate_recommended_threshold(
            purchase_price=convert_to_float(cfg.batteries_purchase_price) or 0.0,
            expected_cycles=(
                v
                if (v := convert_to_int(cfg.batteries_expected_cycles)) is not None
                else 6000
            ),
            usable_capacity=live.battery_usable_capacity_kwh,
        ),
        export_min_price=convert_to_float(cfg.export_electricity_min_price) or 0.0,
        months_winter=list(cfg.months_winter or []),
        house_power_includes_ev=bool(cfg.house_power_includes_ev_charger_power),
        is_read_only=bool(cfg.read_only),
        # EV planned load
        ev_planned_load_enabled=bool(cfg.ev_planned_load_enabled),
        ev_planned_load_connected=bool(live.ev_planned_load_connected),
        ev_planned_load_smart_charging_enabled=bool(
            live.ev_planned_load_smart_charging_enabled
        ),
        ev_planned_load_current_soc_pct=convert_to_float(
            live.ev_planned_load_current_soc_pct
        )
        or 0.0,
        ev_planned_load_target_soc_pct=convert_to_float(
            live.ev_planned_load_target_soc_pct
        )
        or cfg.ev_planned_load_target_soc_fixed,
        ev_planned_load_battery_capacity_kwh=convert_to_float(
            cfg.ev_planned_load_battery_capacity_kwh
        )
        or 0.0,
        ev_planned_load_charger_power_kw=convert_to_float(
            cfg.ev_planned_load_charger_power_kw
        )
        or 0.0,
        ev_planned_load_charger_efficiency_pct=convert_to_float(
            cfg.ev_planned_load_charger_efficiency_pct
        )
        or 100.0,
        ev_planned_load_deadline=live.ev_planned_load_deadline,
        ev_planned_load_base_load_includes_ev=bool(
            cfg.house_power_includes_ev_charger_power
        ),
        # Second EV planned load
        ev_second_planned_load_enabled=bool(cfg.ev_second_planned_load_enabled),
        ev_second_planned_load_connected=bool(live.ev_second_planned_load_connected),
        ev_second_planned_load_smart_charging_enabled=bool(
            live.ev_second_planned_load_smart_charging_enabled
        ),
        ev_second_planned_load_current_soc_pct=convert_to_float(
            live.ev_second_planned_load_current_soc_pct
        )
        or 0.0,
        ev_second_planned_load_target_soc_pct=convert_to_float(
            live.ev_second_planned_load_target_soc_pct
        )
        or cfg.ev_second_planned_load_target_soc_fixed,
        ev_second_planned_load_battery_capacity_kwh=convert_to_float(
            cfg.ev_second_planned_load_battery_capacity_kwh
        )
        or 0.0,
        ev_second_planned_load_charger_power_kw=convert_to_float(
            cfg.ev_second_planned_load_charger_power_kw
        )
        or 0.0,
        ev_second_planned_load_charger_efficiency_pct=convert_to_float(
            cfg.ev_second_planned_load_charger_efficiency_pct
        )
        or 100.0,
        ev_second_planned_load_deadline=live.ev_second_planned_load_deadline,
        ev_second_planned_load_base_load_includes_ev=bool(
            cfg.house_power_includes_ev_charger_power
        ),
        time_discount_rate=0.995,
        # Planner hysteresis (issue #372)
        planner_hysteresis_enabled=bool(cfg.planner_hysteresis_enabled),
        planner_hysteresis_absolute=(
            convert_to_float(cfg.planner_hysteresis_absolute) or 0.0
        ),
        planner_hysteresis_percentage=(
            convert_to_float(cfg.planner_hysteresis_percentage) or 0.0
        ),
        previous_winner_name=previous_winner_name,
        previous_winner_score=previous_winner_score,
    )


def generate_recommendation_intervals(
    interval_minutes: int, total_hours: int
) -> list[HourlyRecommendation]:
    """Generate empty recommendation slots from midnight for ``total_hours`` hours.

    Args:
        interval_minutes: Width of each slot in minutes.
        total_hours: Planning horizon in hours.

    Returns:
        A list of :class:`HourlyRecommendation` objects with all numeric
        fields initialised to ``0.0``.
    """
    now = hsem_now()
    start_time = now.replace(hour=0, minute=0, second=0, microsecond=0)
    steps = int((total_hours * 60) / interval_minutes)

    intervals = []
    for i in range(steps):
        t_start = start_time + timedelta(minutes=i * interval_minutes)
        t_end = t_start + timedelta(minutes=interval_minutes)
        intervals.append(
            HourlyRecommendation(
                avg_house_consumption_kwh=0.0,
                avg_house_consumption_1d_kwh=0.0,
                avg_house_consumption_3d_kwh=0.0,
                avg_house_consumption_7d_kwh=0.0,
                avg_house_consumption_14d_kwh=0.0,
                batteries_charged_kwh=0.0,
                batteries_discharged_kwh=0.0,
                end=t_end,
                estimated_battery_capacity_kwh=0.0,
                estimated_battery_soc_pct=0,
                estimated_cost_currency=0.0,
                estimated_net_consumption_kwh=0.0,
                ev_planned_load_kwh=0.0,
                export_price=0.0,
                grid_export_kwh=0.0,
                grid_import_kwh=0.0,
                import_price=0.0,
                recommendation=None,
                solcast_pv_estimate_kwh=0.0,
                start=t_start,
            )
        )
    return intervals
