name: Python safety check

on:
  push:

env:
  DEP_PATH: ./requirements.txt

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out master
        uses: actions/checkout@v7.0.0

      - name: pyupio/safety-action
        uses: pyupio/safety-action@v1.0.1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
