name: Sync labels

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - .github/sync-labels.yml
  workflow_dispatch:

permissions: read-all

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v5

      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/sync-labels.yml
